import Head from 'next/head'
import { getFeaturedEvents } from '@/dummy-data'
import { EventList } from '@/components/events/event-list'


export default function Home() {
  const featuredEvents = getFeaturedEvents();
  console.log(featuredEvents)
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EventList items={featuredEvents} />
      </main>
    </>
  )
}
