import Head from 'next/head'
import { getFeaturedEvents } from '@/helper/api-util';
import { EventList } from '@/components/events/event-list'


export default function Home({featuredEvents}) {
  console.log(featuredEvents)
  return (
    <>
    {/* <div>Now</div> */}
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EventList items={featuredEvents} />
      </main>
    </>
  )
}


export async function getStaticProps(){
  const featuredEvents = await getFeaturedEvents()

  return {
    props : {
      featuredEvents : featuredEvents
    }
  }
}